addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.4")
addCompilerPlugin("org.spire-math" %% "kind-projector" % "0.9.7")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")
addCompilerPlugin("com.olegpy"     %% "better-monadic-for" % "0.2.4")
